### ISSUE TITLE
Check .net Core upgrade readiness (Github action)

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#2122]
We need to estimate the effort. One possible step could be to the result of one of the tools: (AI suggestions)

name: Check .NET Upgrade Readiness

Replace YourProject.sln with the actual path to your .sln file.

```
on:
  push:
    paths:
      - '**/*.csproj'
      - '**/*.sln'
  workflow_dispatch:

jobs:
  upgrade-check:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install .NET Upgrade Assistant
        run: dotnet tool install -g upgrade-assistant

      - name: Run Upgrade Assistant in analyze mode
        run: |
          upgrade-assistant analyze YourProject.sln --format json > upgrade-report.json

      - name: Upload report artifact
        uses: actions/upload-artifact@v3
        with:
          name: upgrade-report
          path: upgrade-report.json
```
