### ISSUE TITLE
Show/Hide help text on info button

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#234]
If the help text is longer, it is very hard to read it. 

![image](https://user-images.githubusercontent.com/15946467/56028475-7977bf80-5d18-11e9-825f-88c4428255f7.png)

- [x]  Attributes
- [x] Groups/Headlines

for attributes it is just few lines of code to add:

**...\Console\BExIS.Web.Shell\Areas\DCM\Scripts\Form.js**
Add:
```JavaScript
function showHelp(id) {
    $("#" + id).toggle();
}
```

**....\Console\BExIS.Web.Shell\Areas\DCM\Views\Form\_metadataAttributeView.cshtml**
Add new row on top of each Attribute (~line 96)
```HTML
 <table>
+  <tr><td></td><td><div id="help_@idInput" class="help" style="display: none;">@Model.Discription</div></td></tr>
   <tr>
   <td class="metadataAttributeLabel">
```

Change: Add onclick() (~line 341)
```HTML
@if (!string.IsNullOrEmpty(Model.Discription))
 {
<button type="button" title="@Model.Discription" class="bx-function bx-disabled bx-info fa fa-info" onclick="showHelp('help_@idInput');"></button>
}
```

**Comment by geofranzi** [comment]
**Hide/Show all**

![image](https://user-images.githubusercontent.com/15946467/56040823-9079da00-5d37-11e9-9f37-ac516c81640a.png)


![image](https://user-images.githubusercontent.com/15946467/56040800-835ceb00-5d37-11e9-985b-a9246c242f3a.png)



**CSS**
```CSS
#help_container {
    position: relative
}

#help_nested {
    position: absolute;
    top: -4px;
    left: -2px;
    font-size: 200%;
    color: rgba(217, 83, 79, 0.7);
}

#show_help_all, #hide_help_all{
    float: right;
    margin-top: 10px;
    margin-right: 20px;
    cursor: help !important;
}
#hide_all_help {
    display: none;
}
#show_help_all .fa-info, #hide_help_all .fa-ban {
    cursor: pointer !important;
}
```

**From.js**
```JavaScript
function showHelpAll() {
    $(".help").show();
    $("#show_all_help").hide();
    $("#hide_help_all").show();
}

function hideHelpAll() {
    $(".help").hide();
    $("#show_all_help").show();
    $("#hide_help_all").hide();
}
```

**Console\BExIS.Web.Shell\Areas\DCM\Views\Form\MetadataEditor.cshtml**
(Inside and end of 1st Level menu)
```HTML
<div id="show_help_all"><button type="button" title="Show all help information." class="bx-function bx-disabled fa  fa-info " onclick="showHelpAll();"></button></div>
<div id="hide_help_all"><button type="button" title="Hide all help information." class="bx-function bx-disabled" onclick="hideHelpAll();"><i class="fa bx-info" id="help_container"></i><i class="fa fa-ban" id="help_nested"></i></button></div>
```
