### ISSUE TITLE
Upload Wizard: Info messages hidden under header

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#287]
After the change of the header (https://github.com/BEXIS2/Core/issues/142) the layout of the upload wizard does not fit anymore and is somehow hidden.

one possible solution in Console/BExIS.Web.Shell/Themes/Default/Styles/wizard.css

add: 
```CSS
.uploadWizardStep {
    display: flex;
}
```

and remove all 
```CSS
 width: 45%;
 position: absolute;
```
from all elements.
