### ISSUE TITLE
Print the browser shows extra information

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#295]
**Describe the bug**
The search page is open and I want to print to PDF the browser. In many places, a link is shown close to the text.

**To Reproduce**
1. Open the Search page in chrome
2. Right-click on the page
3. select the Print option
4. See the problem

**Screenshots**

The original page:
![original](https://user-images.githubusercontent.com/20185586/64020333-a266e880-cb31-11e9-98a3-2d8183d42223.jpg)

The print page:
![SharedScreenshot](https://user-images.githubusercontent.com/20185586/64020353-aa268d00-cb31-11e9-9eac-2057e0ee7ae4.jpg)

**Comment by DavidBlaa** [comment]
thx for that.

By default, Twitter Bootstrap's print styles include printing links.
````css
/* Bootstrap's way of printing URLs */
@media print {
  a[href]:after {
    content: " (" attr(href) ")";
  }
}
````

If you want to turn that off, you can do
`````css
COPY
/* Don't print link hrefs */
@media print {
  a[href]:after {
    content: none
  }
}

````
